#!/usr/bin/env bash
CMAKEIFY_DOWNLOADS=$1
echo CMakeify downloads cached at $CMAKEIFY_DOWNLOADS

if [ ! -d $CMAKEIFY_DOWNLOADS ]; then
    mkdir $CMAKEIFY_DOWNLOADS
fi

if [ ! -f $CMAKEIFY_DOWNLOADS/cmakeify.jar ]; then
    wget https://github.com/jomof/cmakeify/releases/download/alpha-0.0.1/cmakeify-alpha-0.0.1.jar -O $CMAKEIFY_DOWNLOADS/cmakeify.jar
fi
